#!/bin/bash
#Base vars

pkgname="$2"
opt="$3"
arg="$1"
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BASE='\033[0m'

#Base functions

usage(){
	echo -e "\n:: --> ${GREEN}jeeves-0.3${BASE}\n"
	echo -e "${GREEN}usage: jeeves [arg] PACKAGE [opt]${BASE}"
	echo -e "\nexamples:\n"
	echo -e " - jeeves -S foo [download and install your foo from AUR]"
        echo -e " - jeeves -S foo -nv [download and install your foo from AUR with low verbosity]"
	echo -e " - jeeves -s foo [search for foo in AUR]"
	echo -e " - jeeves -u 'Some message' [upload current dir to origin (AUR) with commit message]\n"
	echo -e "${YELLOW}PLEASE NOTE${BASE} that this is a simple script to see if the package"
	echo -e "that you have just uploaded to AUR installs correctly."
	echo -e "${YELLOW}BEFORE INSTALLING${BASE} a package you have to be sure that you have"
	echo -e "all his required dependencies."
	echo -e "\n${YELLOW}THIS IS NOT A REPLACEMENT OF PACMAN OR PACAUR (OR SIMILARS)${BASE}"
	echo -e "\nEnter 'jeeves --help' to see this :)\n"
}

download() {
	url="https://aur.archlinux.org/cgit/aur.git/snapshot/"
	rm -rf "/tmp/${pkgname}/" #cleanup
	install -d "/tmp/${pkgname}/" && rm -rf /tmp/${pkgname}/* && cd "/tmp/${pkgname}/"
	wget "${url}${pkgname}.tar.gz" 2>/dev/null ##download aur source
	bsdtar -xf "${pkgname}.tar.gz" && cd "${pkgname}"
}

upload(){
	current="$(ls -a)"
	echo -e "\n${GREEN}:: -> Trying to upload current directory...${BASE}"
	sleep 0.75s
	echo ${current} | if grep -q 'PKGBUILD' >/dev/null
	                    then
  				makepkg --printsrcinfo > .SRCINFO
				git add .
				git commit -m "${pkgname}"
				git push origin master
			    else
				echo -e "\n${RED} :: -> Something has gone wrong, are you sure this is a valid directory?${BASE}\n"
			   fi
}

view(){
	echo -e "${GREEN}Choose an editor:${BASE} "
	read editor && "${editor}" PKGBUILD
}

standard(){
  download
	read -p "View PKGBUILD? (y/N)" view
        if [ "${view}" == "y" ]; then
                view
                makepkg -d && sudo pacman -U *.pkg.tar.xz
        else
                makepkg -d && sudo pacman -U *.pkg.tar.xz
        fi

}

standard_nv(){
  download
	read -p "View PKGBUILD? (y/N)" view
        if [ "${view}" == "y" ]; then
                view
                makepkg -d 2>/dev/null && sudo pacman -U *.pkg.tar.xz
        else
                makepkg -d 2>/dev/null && sudo pacman -U *.pkg.tar.xz
        fi

}

search(){
	cower -s "${pkgname}" | awk '/aur\//' | sed $'s/aur\//\e[1m&\e[0m/'
}


###OPERATORS
if [ "${arg}" = "-u" -o "${arg}" = "--upload" ]; then
		if [ -z "${pkgname}" ]; then
			echo -e "\n${RED}Sorry, missing commit message, aborted. :(${BASE}\n" && exit
		else
			upload
		fi
fi


if [ "${arg}" = "--help" ]; then
	usage
fi


if [ "${arg}" = "-S" ]; then
	if [ "${opt}" = "-nv" ]; then
		standard_nv
	else
	  standard
	fi
fi


if [ "${arg}" = "" -o "${arg}" = "--help" -o "${arg}" = "-h" ]; then
		usage
fi


if [ "${arg}" = "-s" -o "${arg}" = "--search" ]; then
	search
fi
